version: '1'
services:
  tstarter1:
    command: "/bin/bash -c /home/node/app/reporter/run.sh"
    build: 
      context: .
    image: "tstarter:v1"
    container_name: tstarter1
    volumes:
      - /storagepool/tstarter/env-commands-1:/env-commands
